/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Form;

import services.categorieservice;
import entities.Categorie;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class CategorieForm extends javax.swing.JInternalFrame {

     private categorieservice Cs;
     private DefaultTableModel model;
     private static int id;
 
    public CategorieForm() {
          initComponents();
          Cs=new categorieservice();
          model=(DefaultTableModel) Tableau_Catgorie.getModel();
          load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void load(){
        model.setRowCount(0);
        for(Categorie c:Cs.findAll()){
            model.addRow(new Object[] {
                c.getId(),
                c.getCode(),
                c.getLibelle(),
                
            });
            
        }
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NouveauCategorie = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Code_Box = new javax.swing.JTextField();
        Libelle_Box = new javax.swing.JTextField();
        Ajouter = new javax.swing.JButton();
        Modifier = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        Liste_Categorie = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tableau_Catgorie = new javax.swing.JTable();

        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        NouveauCategorie.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setText("Nouvelle Categorie");

        jLabel2.setText("Code");

        jLabel3.setText("Libelle");

        Ajouter.setText("Ajouter");
        Ajouter.setToolTipText("");
        Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterActionPerformed(evt);
            }
        });

        Modifier.setText("Modifier");
        Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierActionPerformed(evt);
            }
        });

        Supprimer.setText("Supprimer");
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NouveauCategorieLayout = new javax.swing.GroupLayout(NouveauCategorie);
        NouveauCategorie.setLayout(NouveauCategorieLayout);
        NouveauCategorieLayout.setHorizontalGroup(
            NouveauCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NouveauCategorieLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(NouveauCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(NouveauCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NouveauCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Code_Box, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Libelle_Box, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(NouveauCategorieLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(Ajouter)
                .addGap(87, 87, 87)
                .addComponent(Modifier)
                .addGap(88, 88, 88)
                .addComponent(Supprimer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NouveauCategorieLayout.setVerticalGroup(
            NouveauCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NouveauCategorieLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(NouveauCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Code_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(NouveauCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Libelle_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(NouveauCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ajouter)
                    .addComponent(Modifier)
                    .addComponent(Supprimer))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        Liste_Categorie.setBackground(new java.awt.Color(204, 255, 204));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setText("Liste des Categories");

        Tableau_Catgorie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "Code", "Libelle"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tableau_Catgorie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tableau_CatgorieMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tableau_Catgorie);

        javax.swing.GroupLayout Liste_CategorieLayout = new javax.swing.GroupLayout(Liste_Categorie);
        Liste_Categorie.setLayout(Liste_CategorieLayout);
        Liste_CategorieLayout.setHorizontalGroup(
            Liste_CategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Liste_CategorieLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Liste_CategorieLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        Liste_CategorieLayout.setVerticalGroup(
            Liste_CategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Liste_CategorieLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NouveauCategorie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Liste_Categorie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NouveauCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Liste_Categorie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed
        if(Code_Box.getText().isEmpty() || Libelle_Box.getText().isEmpty()){JOptionPane.showMessageDialog(this, "veillez choisir un client depuit la liste", "Erreur", JOptionPane.ERROR_MESSAGE);}
      else{
        int reponse=JOptionPane.showConfirmDialog(this, "voulez vous vraiment supprimer cette categorie?");
        if(reponse==0){
            if(Cs.delete(Cs.findById(id))){
                JOptionPane.showMessageDialog(this,"la categorie a été bien supprimée !");
                load();
            }
        }}
    }//GEN-LAST:event_SupprimerActionPerformed

    private void AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterActionPerformed
          if(Cs.create(new Categorie(Code_Box.getText(),Libelle_Box.getText()))){
          JOptionPane.showMessageDialog(null, "Categorie ajoute ");
          load();
      }
    }//GEN-LAST:event_AjouterActionPerformed

    private void ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierActionPerformed
        if(Code_Box.getText().isEmpty() || Libelle_Box.getText().isEmpty()  ){JOptionPane.showMessageDialog(this, "veillez choisir une categorie depuit la liste");}
              else{
        String code=Code_Box.getText();
        String libelle=Libelle_Box.getText();
        
        Categorie c=Cs.findById(id);
        c.setCode(code);
        c.setLibelle(libelle);
       
        int reponse=JOptionPane.showConfirmDialog(this, "Voulez vous vraiment modifier cette categrie");
        if(reponse==0){
            if(Cs.update(c)){
                JOptionPane.showMessageDialog(this, "Categorie bien modifié");
                load();
            }
            else{JOptionPane.showMessageDialog(this, "erreur de modification");}
        }
      
        
              }
    }//GEN-LAST:event_ModifierActionPerformed

    private void Tableau_CatgorieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tableau_CatgorieMouseClicked
        id=Integer.parseInt(model.getValueAt(Tableau_Catgorie.getSelectedRow(), 0).toString());
     Code_Box.setText(model.getValueAt(Tableau_Catgorie.getSelectedRow(), 1).toString());
     Libelle_Box.setText(model.getValueAt(Tableau_Catgorie.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_Tableau_CatgorieMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajouter;
    private javax.swing.JTextField Code_Box;
    private javax.swing.JTextField Libelle_Box;
    private javax.swing.JPanel Liste_Categorie;
    private javax.swing.JButton Modifier;
    private javax.swing.JPanel NouveauCategorie;
    private javax.swing.JButton Supprimer;
    private javax.swing.JTable Tableau_Catgorie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
