/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Form;

import services.chambreservice;
import entities.Chambre;
import services.categorieservice;
import entities.Categorie;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class ChambreForm extends javax.swing.JInternalFrame {

         
 

    private chambreservice Chs;
    private categorieservice categorie=new categorieservice();
    private List<Categorie> a=categorie.findAll();
     private DefaultTableModel model;
    private static int id;
    public ChambreForm() {
        initComponents();
        Chs=new chambreservice();
        remplirChambreCategorieBox();
        
        model=(DefaultTableModel) chambreliste.getModel();
        load();
        
	
    }
    
         public void load(){
        model.setRowCount(0);
        for(Chambre ch:Chs.findAll()){
            model.addRow(new Object[] {
                ch.getId(),
                ch.getnumero(),
                ch.getTelephone(),
                ch.getCategorie().getCode(),
               
            });
            
        }
    }
    
    
    
    
        // Méthode pour remplir Chambre_Categorie_Box depuis la base de données
   private void remplirChambreCategorieBox() {
       
    try {
        List<Categorie> categories = categorie.findAll(); // Utilisation de la variable membre existante
        Chambre_Categorie_Box.removeAllItems();
        for (Categorie categorie : categories) {
            Chambre_Categorie_Box.addItem(categorie.getCode());
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erreur lors du remplissage des catégories : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nouveau_Chambre = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Telephone_Box = new javax.swing.JTextField();
        Chambre_Categorie_Box = new javax.swing.JComboBox<>();
        Ajouter_Chambre = new javax.swing.JButton();
        Modifier_Chambre = new javax.swing.JButton();
        Supprimer_Chambre = new javax.swing.JButton();
        Numero_Box = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Liste_Chambre = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chambreliste = new javax.swing.JTable();

        Nouveau_Chambre.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setText("Nouvelle Chambre");

        jLabel2.setText("Telephone");

        jLabel3.setText("Categorie");

        Chambre_Categorie_Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Chambre_Categorie_Box.setToolTipText("");
        Chambre_Categorie_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chambre_Categorie_BoxActionPerformed(evt);
            }
        });

        Ajouter_Chambre.setText("Ajouter");
        Ajouter_Chambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ajouter_ChambreActionPerformed(evt);
            }
        });

        Modifier_Chambre.setText("Modifier");
        Modifier_Chambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modifier_ChambreActionPerformed(evt);
            }
        });

        Supprimer_Chambre.setText("Supprimer");
        Supprimer_Chambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Supprimer_ChambreActionPerformed(evt);
            }
        });

        jLabel5.setText("numero");

        javax.swing.GroupLayout Nouveau_ChambreLayout = new javax.swing.GroupLayout(Nouveau_Chambre);
        Nouveau_Chambre.setLayout(Nouveau_ChambreLayout);
        Nouveau_ChambreLayout.setHorizontalGroup(
            Nouveau_ChambreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Nouveau_ChambreLayout.createSequentialGroup()
                .addGroup(Nouveau_ChambreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Nouveau_ChambreLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(Ajouter_Chambre)
                        .addGap(82, 82, 82)
                        .addComponent(Modifier_Chambre)
                        .addGap(99, 99, 99)
                        .addComponent(Supprimer_Chambre))
                    .addGroup(Nouveau_ChambreLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Nouveau_ChambreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(Nouveau_ChambreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Telephone_Box)
                            .addComponent(Chambre_Categorie_Box, 0, 203, Short.MAX_VALUE)
                            .addComponent(Numero_Box))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        Nouveau_ChambreLayout.setVerticalGroup(
            Nouveau_ChambreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Nouveau_ChambreLayout.createSequentialGroup()
                .addGroup(Nouveau_ChambreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Nouveau_ChambreLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Nouveau_ChambreLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Nouveau_ChambreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Numero_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(6, 6, 6)))
                .addGroup(Nouveau_ChambreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Telephone_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Nouveau_ChambreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Chambre_Categorie_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(Nouveau_ChambreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ajouter_Chambre)
                    .addComponent(Modifier_Chambre)
                    .addComponent(Supprimer_Chambre))
                .addGap(31, 31, 31))
        );

        Liste_Chambre.setBackground(new java.awt.Color(153, 153, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setText("Liste des Chambres");

        chambreliste.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Telephone", "numero", "Categorie Code"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        chambreliste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chambrelisteMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(chambreliste);

        javax.swing.GroupLayout Liste_ChambreLayout = new javax.swing.GroupLayout(Liste_Chambre);
        Liste_Chambre.setLayout(Liste_ChambreLayout);
        Liste_ChambreLayout.setHorizontalGroup(
            Liste_ChambreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Liste_ChambreLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Liste_ChambreLayout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        Liste_ChambreLayout.setVerticalGroup(
            Liste_ChambreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Liste_ChambreLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nouveau_Chambre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Liste_Chambre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Nouveau_Chambre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Liste_Chambre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Chambre_Categorie_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chambre_Categorie_BoxActionPerformed
        
    }//GEN-LAST:event_Chambre_Categorie_BoxActionPerformed

    private void Ajouter_ChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ajouter_ChambreActionPerformed
       if (Numero_Box.getText().isEmpty() || Telephone_Box.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Tous les champs sont obligatoires.", "Erreur", JOptionPane.ERROR_MESSAGE);}
       else{
       Categorie o=new Categorie();
       for(int i=0;i<a.size();i++){
           Categorie ce = a.get(i);
           if(ce.getCode().equals(Chambre_Categorie_Box.getSelectedItem())){
           o=ce;
           break;
           }
       }
 
        if(Chs.create(new Chambre(Numero_Box.getText(),Telephone_Box.getText(),o))){
          JOptionPane.showMessageDialog(null, "Chambre ajoute ");
          load();
    }//GEN-LAST:event_Ajouter_ChambreActionPerformed
        else{JOptionPane.showMessageDialog(null, "Ereeur de creation du chambre");}
    }}
    
    private void Supprimer_ChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Supprimer_ChambreActionPerformed
         if(Numero_Box.getText().isEmpty() || Telephone_Box.getText().isEmpty()){JOptionPane.showMessageDialog(this, "veillez choisir un chambre depuit la liste", "Erreur", JOptionPane.ERROR_MESSAGE);}
      else{
        int reponse=JOptionPane.showConfirmDialog(this, "voulez vous vraiment supprimer cette chambre");
        if(reponse==0){
            if(Chs.delete(Chs.findById(id))){
                JOptionPane.showMessageDialog(this,"le client a été bien supprimé");
                load();
            }
            else{JOptionPane.showMessageDialog(this,"erreur de suppession du chambre");}
        }}
    }//GEN-LAST:event_Supprimer_ChambreActionPerformed

    private void chambrelisteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chambrelisteMousePressed
          
        int row = chambreliste.getSelectedRow();  // Récupérer la ligne sélectionnée dans la table
    if (row != -1) {
        // Récupérer les données de la ligne sélectionnée
        id = (int) chambreliste.getValueAt(row, 0);  // Id de la chambre
        String numero = (String) chambreliste.getValueAt(row, 2);  // Numéro de la chambre
        String telephone = (String) chambreliste.getValueAt(row, 1);  // Téléphone
        String categorieCode = (String) chambreliste.getValueAt(row, 3);  // Code de la catégorie

        // Remplir les champs de texte
        Numero_Box.setText(numero);
        Telephone_Box.setText(telephone);
        
        // Sélectionner la catégorie dans le JComboBox
        for (int i = 0; i < a.size(); i++) {
            Categorie categorie = a.get(i);
            if (categorie.getCode().equals(categorieCode)) {
                Chambre_Categorie_Box.setSelectedItem(categorie.getCode());
                break;
            }
        }
    }
     
    }//GEN-LAST:event_chambrelisteMousePressed

    
    
    
    
    
    private void Modifier_ChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modifier_ChambreActionPerformed
            // Vérification des champs obligatoires
    if (Numero_Box.getText().isEmpty() || Telephone_Box.getText().isEmpty() || Chambre_Categorie_Box.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs, y compris la catégorie.", "Erreur", JOptionPane.ERROR_MESSAGE);
        return; // Arrêter l'exécution si des champs sont vides
    }

    // Récupérer les informations du formulaire
    String numero = Numero_Box.getText();
    String telephone = Telephone_Box.getText();
    String codeCategorie = (String) Chambre_Categorie_Box.getSelectedItem(); // Récupérer le code de la catégorie

    // Trouver l'objet Categorie correspondant au code sélectionné
    Categorie o = null;
    for (int i = 0; i < a.size(); i++) {
        Categorie ce = a.get(i);
        if (ce.getCode().equals(codeCategorie)) {
            o = ce; // Trouver la catégorie
            break;
        }
    }

    // Vérifier si la catégorie a été trouvée
    if (o == null) {
        JOptionPane.showMessageDialog(this, "Catégorie non trouvée.", "Erreur", JOptionPane.ERROR_MESSAGE);
        return; // Si la catégorie n'est pas trouvée, arrêter l'exécution
    }

    // Trouver la chambre à modifier
    System.out.println("ID de la chambre à modifier : " + id); 
    Chambre c = Chs.findById(id);
    if (c == null) {
        JOptionPane.showMessageDialog(this, "Chambre non trouvée.", "Erreur", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Mettre à jour les informations de la chambre
    c.setnumero(numero);
    c.setTelephone(telephone);
    c.setCategorie(o); // Assigner la nouvelle catégorie

    // Demander confirmation de la modification
    int reponse = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment modifier cette chambre?");
    if (reponse == 0) { // Si l'utilisateur confirme
        if (Chs.update(c)) { // Mettre à jour la chambre dans la base de données
            JOptionPane.showMessageDialog(this, "Chambre bien modifiée");
            load(); // Recharger les données ou actualiser l'affichage
        } else {
            JOptionPane.showMessageDialog(this, "Erreur de modification de la chambre", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_Modifier_ChambreActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajouter_Chambre;
    private javax.swing.JComboBox<String> Chambre_Categorie_Box;
    private javax.swing.JPanel Liste_Chambre;
    private javax.swing.JButton Modifier_Chambre;
    private javax.swing.JPanel Nouveau_Chambre;
    private javax.swing.JTextField Numero_Box;
    private javax.swing.JButton Supprimer_Chambre;
    private javax.swing.JTextField Telephone_Box;
    private javax.swing.JTable chambreliste;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
