/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Form;
import services.clientservice;
import entities.Client;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author hp
 */
public class ClientForm extends javax.swing.JInternalFrame {

    private clientservice c;
    private DefaultTableModel model;
    private static int id;

    public ClientForm() {
        initComponents();
        c=new clientservice();
        model=(DefaultTableModel) listeclient.getModel();
        load();
        
    }
   
     public void load(){
        model.setRowCount(0);
        for(Client cl:c.findAll()){
            model.addRow(new Object[] {
                cl.getId(),
                cl.getNom(),
                cl.getPrenom(),
                cl.getTelephone(),
                cl.getEmail(),
                cl.getCIN()
            });
            
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NouveauClient = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NomBox = new javax.swing.JTextField();
        PrenomBox = new javax.swing.JTextField();
        TelephoneBox = new javax.swing.JTextField();
        EmailBox = new javax.swing.JTextField();
        Ajouter_Client = new javax.swing.JButton();
        Modifier_Client = new javax.swing.JButton();
        Supprimer_Client = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CIN_Box = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ListeClient = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeclient = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        NouveauClient.setBackground(new java.awt.Color(255, 204, 255));
        NouveauClient.setName("Nouveau Client"); // NOI18N

        jLabel1.setText("NOM");

        jLabel2.setText("PRENOM");

        jLabel3.setText("TELEPHONE");

        jLabel4.setText("EMAIL");

        PrenomBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrenomBoxActionPerformed(evt);
            }
        });

        TelephoneBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelephoneBoxActionPerformed(evt);
            }
        });

        Ajouter_Client.setText("AJOUTER");
        Ajouter_Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ajouter_ClientActionPerformed(evt);
            }
        });

        Modifier_Client.setText("MODIFIER");
        Modifier_Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modifier_ClientActionPerformed(evt);
            }
        });

        Supprimer_Client.setText("SUPPRIMER");
        Supprimer_Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Supprimer_ClientActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel6.setText("Nouveau Client");

        jLabel7.setText("CIN");

        javax.swing.GroupLayout NouveauClientLayout = new javax.swing.GroupLayout(NouveauClient);
        NouveauClient.setLayout(NouveauClientLayout);
        NouveauClientLayout.setHorizontalGroup(
            NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NouveauClientLayout.createSequentialGroup()
                .addGroup(NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NouveauClientLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NouveauClientLayout.createSequentialGroup()
                            .addGap(235, 235, 235)
                            .addComponent(Modifier_Client)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                            .addComponent(Supprimer_Client))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NouveauClientLayout.createSequentialGroup()
                            .addGroup(NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(NouveauClientLayout.createSequentialGroup()
                                    .addGap(81, 81, 81)
                                    .addGroup(NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(21, 21, 21))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NouveauClientLayout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addGroup(NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NouveauClientLayout.createSequentialGroup()
                                            .addComponent(Ajouter_Client)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NouveauClientLayout.createSequentialGroup()
                                            .addGroup(NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel7))
                                            .addGap(32, 32, 32)))))
                            .addGroup(NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TelephoneBox, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                .addComponent(PrenomBox)
                                .addComponent(NomBox)
                                .addComponent(EmailBox)
                                .addComponent(CIN_Box)))))
                .addGap(0, 131, Short.MAX_VALUE))
        );
        NouveauClientLayout.setVerticalGroup(
            NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NouveauClientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(3, 3, 3)
                .addGroup(NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrenomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TelephoneBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CIN_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ajouter_Client)
                    .addComponent(Modifier_Client)
                    .addComponent(Supprimer_Client))
                .addContainerGap())
        );

        ListeClient.setBackground(new java.awt.Color(255, 204, 255));
        ListeClient.setForeground(new java.awt.Color(255, 204, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Liste Client");

        listeclient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nom", "Prenom", "Telephone", "Email", "CIN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        listeclient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeclientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listeclient);

        javax.swing.GroupLayout ListeClientLayout = new javax.swing.GroupLayout(ListeClient);
        ListeClient.setLayout(ListeClientLayout);
        ListeClientLayout.setHorizontalGroup(
            ListeClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListeClientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(500, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListeClientLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        ListeClientLayout.setVerticalGroup(
            ListeClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListeClientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NouveauClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ListeClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(NouveauClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ListeClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrenomBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrenomBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrenomBoxActionPerformed

    private void Modifier_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modifier_ClientActionPerformed
              if(NomBox.getText().isEmpty() ){JOptionPane.showMessageDialog(this, "veillez choisir un client depuit la liste");}
              else{
        String nom=NomBox.getText();
        String prenom=PrenomBox.getText();
        String tel=TelephoneBox.getText();
        String mail=EmailBox.getText();
        String cin=CIN_Box.getText();
        Client cl=c.findById(id);
        cl.setNom(nom);
        cl.setPrenom(prenom);
        cl.setTelephone(tel);
        cl.setEmail(mail);
        cl.setCIN(cin);
        int reponse=JOptionPane.showConfirmDialog(this, "Voulez vous vraiment modifier ce client");
        if(reponse==0){
            if(c.update(cl)){
                JOptionPane.showMessageDialog(this, "Client bien modifié");
                load();
            }
            else{JOptionPane.showMessageDialog(this, "erreur de modification");}
        }
      
        
              }
    }//GEN-LAST:event_Modifier_ClientActionPerformed

    private void TelephoneBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelephoneBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelephoneBoxActionPerformed

    private void Ajouter_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ajouter_ClientActionPerformed
    String nom = NomBox.getText();
    String prenom = PrenomBox.getText();
    String telephone = TelephoneBox.getText();
    String email = EmailBox.getText();
    String cin = CIN_Box.getText();

    if (nom.isEmpty() || prenom.isEmpty() || telephone.isEmpty() || email.isEmpty() || cin.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Tous les champs sont obligatoires.", "Erreur", JOptionPane.ERROR_MESSAGE);
    } else {
        Client client = new Client(nom, prenom, telephone, email, cin);
        c.create(client);
        JOptionPane.showMessageDialog(this, "Client ajouté avec succès.");
        load();
    }
    }//GEN-LAST:event_Ajouter_ClientActionPerformed

    private void Supprimer_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Supprimer_ClientActionPerformed
      if(NomBox.getText().isEmpty() ){JOptionPane.showMessageDialog(this, "veillez choisir un client depuit la liste", "Erreur", JOptionPane.ERROR_MESSAGE);}
      else{
        int reponse=JOptionPane.showConfirmDialog(this, "voulez vous vraiment supprimer ce client");
        if(reponse==0){
            if(c.delete(c.findById(id))){
                JOptionPane.showMessageDialog(this,"le client a été bien supprimé");
                load();
            }
        }}
    }//GEN-LAST:event_Supprimer_ClientActionPerformed

    private void listeclientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeclientMouseClicked
        id=Integer.parseInt(model.getValueAt(listeclient.getSelectedRow(), 0).toString());
     NomBox.setText(model.getValueAt(listeclient.getSelectedRow(), 1).toString());
     PrenomBox.setText(model.getValueAt(listeclient.getSelectedRow(), 2).toString());
     TelephoneBox.setText(model.getValueAt(listeclient.getSelectedRow(), 3).toString());
     EmailBox.setText(model.getValueAt(listeclient.getSelectedRow(), 4).toString());
     CIN_Box.setText(model.getValueAt(listeclient.getSelectedRow(), 5).toString());
    }//GEN-LAST:event_listeclientMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajouter_Client;
    private javax.swing.JTextField CIN_Box;
    private javax.swing.JTextField EmailBox;
    private javax.swing.JPanel ListeClient;
    private javax.swing.JButton Modifier_Client;
    private javax.swing.JTextField NomBox;
    private javax.swing.JPanel NouveauClient;
    private javax.swing.JTextField PrenomBox;
    private javax.swing.JButton Supprimer_Client;
    private javax.swing.JTextField TelephoneBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listeclient;
    // End of variables declaration//GEN-END:variables
}
